language: node_js
node_js:
  - "8"
before_script:
  - npm install -g karma-cli
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - cd test
script: karma start karma.conf.js --single-run
